opencor/opencor

src/plugins/api/BioSignalMLAPI/CMakeLists.txt
=> Drop `_d` postfix in Windows' debug binaries.

src/plugins/miscellaneous/Core/src/corecliutils.cpp, src/plugins/miscellaneous/Core/src/corecliutils.cpp.inl, src/plugins/miscellaneous/Core/src/corecliutils.h, src/plugins/miscellaneous/Core/src/corecliutils.h.inl, src/plugins/miscellaneous/Core/src/file.cpp, src/plugins/miscellaneous/Core/tests/generaltests.cpp
=> Detecting file changes doesn't work with non-text files (#882)

src/misc/cliapplication.cpp
=> All CLI arguments that follow a command need to be passed to the command

src/misc/cliapplication.cpp
This also makes a small change to the CLI syntax.
Resolves issue #1168.
=> Always detect a missing plugin on the command line.

CMakeLists.txt, src/plugins/api/BioSignalMLAPI/CMakeLists.txt
This should complete issue #1313.
=> Use new packaging system for BioSignalML API plugin.

CMakeLists.txt, src/plugins/thirdParty/Qwt/CMakeLists.txt
See https://github.com/opencor/qwt/pull/1.
=> Qwt: don't set `_USE_MATH_DEFINES` for MSVC as `qmath.h` does so

src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewwidget.cpp, src/plugins/support/SimulationSupport/src/simulation.cpp
Forgot to clean that up when working on issue #1491...!
=> Some minor cleaning up

src/plugins/widget/EditorWidget/src/editorwidgetfindreplacewidget.cpp, src/plugins/widget/EditorWidget/src/editorwidgetfindreplacewidget.h
My bad, I cleaned up some code and remove something that I should
clearly not have been removed!
=> Editor widget: make sure that people know whether we can find/replace

src/plugins/dataStore/BioSignalMLDataStore/src/biosignalmldatastoreexporter.cpp, src/plugins/dataStore/CSVDataStore/src/csvdatastoreexporter.cpp, src/plugins/datastoreinterface.h, src/plugins/miscellaneous/Core/src/corecliutils.cpp, src/plugins/miscellaneous/Core/src/corecliutils.h, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewsimulationwidget.cpp, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewsimulationwidget.h
That version can indeed come handy when testing things where we need a
fixed delay, for example.
=> Various minor improvements

src/mainwindow.cpp, src/plugins/dataStore/DataStore/src/datastoredialog.cpp, src/plugins/miscellaneous/Core/src/centralwidget.cpp, src/plugins/miscellaneous/Core/src/tabbarwidget.cpp, src/plugins/organisation/FileOrganiserWindow/src/fileorganiserwindowwidget.cpp, src/plugins/organisation/FileOrganiserWindow/src/fileorganiserwindowwidget.h, src/plugins/organisation/PMRWindow/src/pmrwindowwidget.cpp, src/plugins/organisation/PMRWorkspacesWindow/src/pmrworkspaceswindowwidget.cpp, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewinformationgraphpanelandgraphswidget.cpp, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewsimulationwidget.cpp, src/plugins/support/PMRSupport/src/pmrwebservice.cpp, src/plugins/widget/GraphPanelWidget/src/graphpanelswidget.cpp, src/plugins/widget/GraphPanelWidget/src/graphpanelwidget.cpp
Indeed, it was complaining that `item` could be null, even though it
couldn’t be in practice. Still, better be safe than sorry.
=> Satisfy Xcode analysis

src/plugins/editing/RawSEDMLView/src/rawsedmlviewwidget.cpp, src/plugins/simulation/SimulationExperimentView/i18n/SimulationExperimentView_fr.ts, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewsimulationwidget.cpp, src/plugins/support/SEDMLSupport/src/sedmlfile.cpp, src/plugins/support/SEDMLSupport/src/sedmlfileissue.h, src/plugins/support/SimulationSupport/i18n/SimulationSupport_fr.ts, src/plugins/support/SimulationSupport/src/simulation.cpp, src/plugins/support/SimulationSupport/src/simulation.h, src/plugins/widget/EditorWidget/src/editorlistwidget.cpp, src/plugins/widget/EditorWidget/src/editorlistwidget.h
I trust this does the right things -- it's been tested with both valid and invalid CellML and SED-ML files.
=> Generalise reporting of a simulation's issues (#2080).

CMakeLists.txt, src/plugins/thirdParty/libgit2/CMakeLists.txt
=> libgit2: new binaries for version 0.28.1

src/plugins/editing/CellMLAnnotationView/res/qualifierInformation.html
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/opencor/opencor/file/master/src/plugins/editing/CellMLAnnotationView/res/qualifierInformation.html).
=> Apply fixes from CodeFactor

src/plugins/support/PythonSupport/CMakeLists.txt, src/plugins/support/PythonSupport/tests/data/importstests.py, src/plugins/support/PythonSupport/tests/data/windows/debug/importstests.out, src/plugins/support/PythonSupport/tests/importstests.cpp, src/plugins/support/PythonSupport/tests/importstests.h, src/plugins/thirdParty/Python/CMakeLists.txt
The old one didn't contain lzma!
=> Python package: update our macOS binary (#2256)

doc/downloads/index.js, src/plugins/thirdParty/OpenSSL/CMakeLists.txt
=> OpenSSL: upgrade to version 1.1.1h (#2399)

CMakeLists.txt, src/3rdparty/QtWebKit/CMakeLists.txt, src/plugins/thirdParty/CellMLAPI/CMakeLists.txt, src/plugins/thirdParty/LLVMClang/CMakeLists.txt, src/plugins/thirdParty/OpenSSL/CMakeLists.txt, src/plugins/thirdParty/SUNDIALS/CMakeLists.txt, src/plugins/thirdParty/libgit2/CMakeLists.txt, src/plugins/thirdParty/zlib/CMakeLists.txt
=> macOS: build all our third-party libraries using our minium supported deployment target (#2402)

doc/downloads/index.js, doc/downloads/previousSnapshots.js, src/plugins/miscellaneous/PythonConsoleWindow/src/pythonconsolewindow.cpp
=> Python Console window: automatically reload imported modules (#2466)

doc/downloads/index.js, src/plugins/thirdParty/libNuML/CMakeLists.txt, src/plugins/thirdParty/libNuML/tests/tests.cpp
=> libNuML: upgrade to version 1.1.4 (#2470)

src/3rdparty/linux/mesa/CMakeLists.txt
=> Mesa: upgrade to version 21.0.3 (#2471)

doc/downloads/index.js, doc/downloads/previousSnapshots.js, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewsimulationwidget.cpp
=> Simulation Experiment view: cannot export a CellML 1.1 model to a COMBINE archive on Windows (#2478)

doc/downloads/index.js, src/plugins/thirdParty/Qwt/CMakeLists.txt
=> Qwt: upgrade to version 6.1.6 (#2483)

doc/downloads/index.js, doc/downloads/previousSnapshots.js, doc/whatIsNew.js, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewinformationwidget.cpp, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewinformationwidget.h, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewsimulationwidget.cpp
=> Simulation Experiment view: crash when trying to clear the graph panel (#2497)

doc/downloads/index.js, doc/downloads/previousSnapshots.js, src/plugins/thirdParty/LLVMClang/CMakeLists.txt
=> LLVM+Clang: upgrade to version 12.0.1 (#2515)

doc/downloads/index.js, src/plugins/widget/GraphPanelWidget/src/graphpanelplotwidget.cpp
=> Graph Panel widget: round off axes values whenever possible (#2518)

doc/downloads/index.js, doc/whatIsNew.js, src/plugins/simulation/SimulationExperimentView/i18n/SimulationExperimentView_fr.ts, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewinformationparameterswidget.cpp, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewinformationparameterswidget.h
=> Simulation Experiment view: add a way to plot a parameter against the last used parameter (#2521)

doc/downloads/index.js
=> KaTeX: upgrade to version 0.13.13

doc/downloads/index.js, src/plugins/dataStore/DataStore/src/datastorepythonwrapper.cpp
=> Python support: ensure that data store manipulations are safe

doc/downloads/index.js, doc/downloads/previousSnapshots.js, src/plugins/support/SimulationSupport/src/simulationsupportpythonwrapper.cpp, src/plugins/support/SimulationSupport/src/simulationsupportpythonwrapper.h
=> Python support: improve the way we check whether a simulation is valid before running it

.github/workflows/ci.yml, .github/workflows/config.json, src/plugins/support/PythonSupport/tests/data/basictests.out, src/plugins/support/PythonSupport/tests/data/basictests.py
=> Rely on GitHub actions for our CI tests

doc/downloads/index.js, src/plugins/miscellaneous/Core/src/centralwidget.cpp
=> Simulation Experiment view: remote SED-ML files can't be fully reloaded

CMakeLists.txt, doc/downloads/index.js, doc/downloads/previousSnapshots.js
=> Windows installer: update the Python shebangs upon having installed OpenCOR

doc/downloads/index.js, doc/whatIsNew.js, src/plugins/support/CellMLSupport/src/cellmlfilecellml10exporter.cpp, src/plugins/support/CellMLSupport/src/cellmlfilecellml10exporter.h, src/plugins/tools/CellMLTools/tests/data/duplicate_ids/main.cellml, src/plugins/tools/CellMLTools/tests/data/duplicate_ids/main.out, src/plugins/tools/CellMLTools/tests/data/duplicate_ids/other_model.cellml, src/plugins/tools/CellMLTools/tests/data/duplicate_ids/real_model.cellml, src/plugins/tools/CellMLTools/tests/data/duplicate_ids/sub_model.cellml, src/plugins/tools/CellMLTools/tests/data/duplicate_ids/sub_sub_model.cellml, src/plugins/tools/CellMLTools/tests/tests.cpp
=> CellML tools: fixed an issue with duplicate ids following the export of a CellML 1.1 model to CellML 1.0

doc/downloads/index.js, src/misc/furtherinitialize.cpp.inl, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewsimulationwidget.cpp, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewsimulationwidget.h
=> Simulation Experiment view: a SED-ML file / COMBINE archive is considered modified upon opening when it has no plots

.github/workflows/cd.yml, .github/workflows/ci.yml, cd, cd.bat
=> Documentation: put our general documentation in its own repository

src/plugins/miscellaneous/Core/src/corecliutils.cpp, src/plugins/tools/CellMLTools/src/cellmltoolsplugin.cpp, src/plugins/tools/CellMLTools/src/cellmltoolsplugin.h
=> CellML tools: suggest a better file name when exporting a remote CellML 1.1 file to CellML 1.0

src/plugins/thirdParty/libgit2/CMakeLists.txt
=> libgit2: upgrade to version 1.3.0

.github/workflows/ci.yml, src/3rdparty/linux/mesa/CMakeLists.txt
=> Mesa: upgrade to version 21.2.3

src/plugins/support/CellMLSupport/src/cellmlfileissue.cpp, src/plugins/tools/CellMLTools/src/cellmltoolsplugin.cpp
=> Raw CellML view: messages may show some HTML code (#2595)

CMakeLists.txt, cmake/common.cmake
This replaces PR #2597 for which, for some reasons, GitHub Actions couldn't install Qt anymore on macOS...!?
=> Cleaning up

distrib/linux/application.in, distrib/linux/ipython, distrib/linux/jupyter, distrib/linux/jupyterconsole.in, distrib/linux/jupyterlab, distrib/linux/jupyternotebook, distrib/linux/pythonshell.in, distrib/linux/runipython, distrib/linux/runjupyter, distrib/macos/application.in, distrib/macos/ipython.in, distrib/macos/jupyter.in, distrib/macos/jupyterconsole.in, distrib/macos/jupyterlab.in, distrib/macos/jupyternotebook.in, distrib/macos/pythonshell.in, distrib/macos/runipython.in, distrib/macos/runjupyter.in, package
=> Distribution scripts do not properly escape input arguments

src/plugins/thirdParty/Python/scripts/set_python_path.py
=> fix: handle additional types of errors in updating scripts

src/plugins/support/PMRSupport/src/pmrworkspace.cpp, src/plugins/thirdParty/libgit2/CMakeLists.txt
=> libgit2: upgrade to version 1.4.2

src/3rdparty/linux/mesa/CMakeLists.txt
=> Mesa: upgrade to version 21.3.8

CMakeLists.txt, cmake/common.cmake, src/plugins/thirdParty/OpenSSL/CMakeLists.txt, src/plugins/thirdParty/Python/CMakeLists.txt, src/plugins/thirdParty/libgit2/CMakeLists.txt
=> OpenSSL: upgrade to version 3.0.2

src/plugins/thirdParty/QScintilla/CMakeLists.txt
=> QScintilla: upgrade to version 2.13.2

src/plugins/thirdParty/libSEDML/CMakeLists.txt, src/plugins/thirdParty/libSEDML/tests/tests.cpp
=> libSEDML: upgrade to version 2.0.31

src/plugins/thirdParty/OpenSSL/CMakeLists.txt
=> OpenSSL: upgrade to version 3.0.3

src/plugins/thirdParty/QScintilla/CMakeLists.txt
=> QScintilla: upgrade to version 2.13.3

src/plugins/thirdParty/libgit2/CMakeLists.txt
=> libgit2: upgrade to version 1.4.3

src/plugins/thirdParty/libNuML/CMakeLists.txt, src/plugins/thirdParty/libNuML/tests/tests.cpp
=> libNuML: upgrade to version 1.1.6

src/3rdparty/linux/mesa/CMakeLists.txt
=> Mesa: upgrade to version 22.1.0

src/plugins/thirdParty/zlib/CMakeLists.txt
=> zlib: upgrade to version 1.2.12

CMakeLists.txt, cmake/common.cmake, src/plugins/thirdParty/Python/CMakeLists.txt, src/plugins/thirdParty/PythonPackages/CMakeLists.txt
=> Python: package the VC runtime on Windows

CMakeLists.txt, src/3rdparty/QtWebKit/CMakeLists.txt, src/plugins/thirdParty/OpenSSL/CMakeLists.txt, src/plugins/thirdParty/Python/CMakeLists.txt, src/plugins/thirdParty/QScintilla/CMakeLists.txt, src/plugins/thirdParty/Qwt/CMakeLists.txt, src/plugins/thirdParty/Zinc/CMakeLists.txt, src/plugins/thirdParty/libgit2/CMakeLists.txt, src/plugins/thirdParty/zlib/CMakeLists.txt
=> OpenSSL: use version 1.1.1 rather than version 3.0

src/plugins/support/CellMLSupport/src/cellmlfile.cpp, src/plugins/support/CellMLSupport/src/cellmlfile.h
=> CellML support: wrong error messages during the full instantiation of a model's imports

src/plugins/thirdParty/OpenSSL/CMakeLists.txt
=> OpenSSL: upgrade to version 1.1.1s

.github/workflows/ci.yml, src/plugins/thirdParty/LLVMClang/CMakeLists.txt
=> LLVM+Clang: upgrade to version 14.0.6

src/plugins/thirdParty/libgit2/CMakeLists.txt
=> libgit2: upgrade to version 1.5.0

src/plugins/thirdParty/libSEDML/CMakeLists.txt, src/plugins/thirdParty/libSEDML/tests/tests.cpp
=> libSEDML: upgrade to version 2.0.32

src/3rdparty/linux/mesa/CMakeLists.txt
=> Mesa: upgrade to version 22.2.2

src/plugins/thirdParty/zlib/CMakeLists.txt
=> zlib: upgrade to version 1.2.13

CMakeLists.txt, distrib/linux/application.in, distrib/linux/ipython, distrib/linux/jupyter, distrib/linux/jupyterconsole.in, distrib/linux/jupyterlab, distrib/linux/jupyternotebook, distrib/linux/pythonshell.in
=> Linux: support Ubuntu 22.04 LTS

src/plugins/widget/ToolBarWidget/src/toolbarwidget.cpp
=> Preferences: to change the style crashes OpenCOR

CMakeLists.txt
=> Release OpenCOR 0.7

CMakeLists.txt, src/plugins/thirdParty/libSEDML/src/libsedmlbegin.h
=> macOS: always build for x86_64

CMakeLists.txt, cmake/builddocumentation.cmake.in, cmake/common.cmake
=> Mimic libOpenCOR when it comes to building our documentation

src/3rdparty/QtWebKit/CMakeLists.txt, src/3rdparty/linux/icu/CMakeLists.txt, src/3rdparty/linux/mesa/CMakeLists.txt
=> Improve the compilation of external projects

src/plugins/support/SEDMLSupport/src/sedmlfile.cpp
=> SED-ML support: OpenCOR crashes when closing a remote CellML file opened from a remote SED-ML file

src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewinformationgraphpanelandgraphswidget.cpp, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewpreferenceswidget.cpp
=> Graph Panel widget: to enable/disable some properties from the context menu doesn't work anymore (#2758)

src/plugins/widget/GraphPanelWidget/i18n/GraphPanelWidget_fr.ts, src/plugins/widget/GraphPanelWidget/src/graphpanelplotwidget.cpp, src/plugins/widget/GraphPanelWidget/src/graphpanelplotwidget.h, src/plugins/widget/GraphPanelWidget/src/graphpanelswidget.cpp
=> Simulation Experiment view: synchronise axes of the same type

src/plugins/miscellaneous/Core/src/propertyeditorwidget.cpp, src/plugins/miscellaneous/Core/src/propertyeditorwidget.h, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewsimulationwidget.cpp, src/plugins/widget/GraphPanelWidget/src/graphpanelplotwidget.cpp, src/plugins/widget/GraphPanelWidget/src/graphpanelplotwidget.h
=> Graph Panel widget: the range of some plots' axes doesn't get set properly

.github/workflows/cd.yml
=> Have packages automatically created for snapshots and official versions

src/plugins/editing/CellMLTextView/src/cellmltextviewparser.cpp
=> CellMLTextViewParser: make sure that we have a node to which to append a comment

src/plugins/solver/CVODESolver/src/cvodesolver.cpp
=> CVODE: improve the computation of rates

src/plugins/dataStore/CSVDataStore/src/csvdatastoreexporter.cpp
=> CSV: export data with more precision

src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewsimulationwidget.cpp, src/plugins/widget/GraphPanelWidget/src/graphpanelplotwidget.cpp, src/plugins/widget/GraphPanelWidget/src/graphpanelplotwidget.h, src/plugins/widget/GraphPanelWidget/src/graphpanelswidget.cpp
=> Simulation view: some graph panels don't have the correct range upon running a model

src/plugins/dataStore/DataStore/src/datastorepythonwrapper.cpp, src/plugins/dataStore/DataStore/src/datastorepythonwrapper.h, src/plugins/simulation/SimulationExperimentView/src/simulationexperimentviewinformationparameterswidget.cpp, src/plugins/support/PythonSupport/tests/data/utils.py, src/plugins/support/SimulationSupport/src/simulation.cpp
=> Python: provide a way to release values (retrieved as a NumPy array) that are not needed anymore

CMakeLists.txt, distrib/linux/ipython, distrib/linux/jupyter, distrib/linux/jupyterconsole.in, distrib/linux/jupyterlab, distrib/linux/jupyternotebook, distrib/linux/pip, distrib/linux/python, distrib/linux/runipython, distrib/linux/runjupyter, distrib/macos/pip.in, distrib/macos/python.in, distrib/windows/pip.bat, distrib/windows/python.bat, src/plugins/support/PythonSupport/src/pythonsupportplugin.cpp, src/plugins/thirdParty/Python/CMakeLists.txt
=> Python: added some scripts to run Python itself and pip

src/plugins/dataStore/DataStore/src/datastorepythonwrapper.cpp, src/plugins/dataStore/DataStore/src/datastorepythonwrapper.h, src/plugins/datastoreinterface.cpp, src/plugins/datastoreinterface.h, src/plugins/support/PythonSupport/tests/data/utils.py, src/plugins/support/SimulationSupport/src/simulation.cpp, src/plugins/support/SimulationSupport/src/simulation.h, src/plugins/support/SimulationSupport/src/simulationsupportpythonwrapper.cpp, src/plugins/support/SimulationSupport/src/simulationsupportpythonwrapper.h
=> Python: include the ability to easily release all values at once

.github/workflows/cd.yml
=> CD: use New Zealand time

CMakeLists.txt, src/plugins/miscellaneous/HelpWindow/CMakeLists.txt, src/plugins/thirdParty/PythonPackages/CMakeLists.txt, src/plugins/widget/GraphPanelWidget/src/graphpanelplotwidget.cpp
=> CMake: address various issues

CMakeLists.txt
=> Release OpenCOR 0.8

src/plugins/widget/GraphPanelWidget/src/graphpanelplotwidget.cpp, src/plugins/widget/GraphPanelWidget/src/graphpanelplotwidget.h
=> Simulation Experiment view: hangs up when running the CiPA model

CMakeLists.txt
=> Release OpenCOR 0.8.1

CMakeLists.txt
=> Release OpenCOR 0.8.2
